GET http://localhost:3000

###

GET http://localhost:3000/bye

###

POST http://localhost:3000/login
Content-Type: application/json 
//header : what is the content type

{
    "username": "mimi",
    "password": "000000"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "mimi",
    "password": "000000",
    "name": "Mimi Lana",
    "email": "mimilana@yahoo.com"
}
