GET http://localhost:3000

###

GET http://localhost:3000/bye

###

POST http://localhost:3000/register

###

POST http://localhost:3000/login
Content-Type: application/json 
//header : what is the content type

{
    "username": "awin",
    "password": "password"
}
